hindi_slangs = [
    "teri maa ki bhosde mai mdh chana masala daal ke tere baap ko vo spicy bhosda khila dunga.",
    "gand mai vimal ki goli bna kar de dunga, bhencho teri gaand mai railway station ka fatak de dunga.",
    "100000000000000000000000000000 baap ki najais olad randi kay beez chinnale, teri ma ki chut maru.",
    "teri ma ki gand me hathi ka lund dalke asa chodunga na bacha hojayega. Kasam se bol rha hu, suar ke lund se chudwaungu bhosdike.",
    "madarchod bhosdke esa lagta hai apne hii taaate kaat ke chipka diya apni shakal dekh lodee jese shakal aur gand me hai aakal.",
    "madarchod teri bahan ki chut marke teri tatti jesi shakal pe pad dunga bhen ki lode chutiye.",
    "maa ki lode, tere jese randi ka baccho ko bachpan mai maar dena chiye.",
    "teri ma randi, tera baap hizda, kaali gaand kay khade baal jhaatu randi kay chodu.",
    "bhenchod baap se panga matt le warna maa chodh di jayegi.",
    "teri sexy bhen ki chut me mai loda daal kar raat bhar jor jor se chodunga.",
    "teri bhen ki tight chut ko lapak lapak kar speed se chod du.",
    "bhosadchod teri maiya ki gaand me teri bahan ko le ghuskar itne bache paida karunga ki tujhe ye decide karte karte heart attack a jayega ki tu unka mama hai ya bhaiya.",
    "teri maa ko mere kutte se chudwaya tha toh gaand ke andar ek choti si funsi ho gayi thi, aaj bhi usse khujlaane use biscuit de de ke bulati hai",
    "aaj mai kha ke chawal, teri maiya ki bhosdi, appne lund se karu pagal.",
    "aaj mai banke tera papa, teri ma ka nikalu randapa.",
    "jungle jungle mai chale, jungle me mile mujhe kfan, tere jhatu bache ki ma ki chut marke karu chat me dafan.",
    "aaj mai piyunga cigarette, chahe mujhe khasi ho jye, teri maiya ki bhosdi faad ke rahunga, chahe mujhe fasi ho jaye.",
    "delhi ka laal kila up ki goli, teri maa chodunga khol k choli.",
    "chalti thi bicycle, udti thi dhool, teri mummy ko chodke karu sab paise vasool.",
    "teri ma baithi tel laga ke, maine dia lund ghuma ke, teri ma bhagi chut daba ke.",
    "aaj mai pii kar pepsi, teri randi maiyya ko apne lund se banau sexy.",
    "aaj mai peeke daru teri ma ki chut pe chappal maru.",
    "oye bhen ke lode teri ma ko bnake rand uski marunga din raat gand, uske muh me dunga apne dono aand chod chodke bna dunga use saand tatti khani aurat deya putran.",
    "aj mai khake nimbu ka achar, teri randi ma ko chod chodke kar dunga lachar.",
    "jaameen se nikla aalluu tumhari mummy ko  chode bhalu.",
    "nam hai mera sex master, loda ka weight 56 kilo loda tinkgaauu kuhwaaa khud jaaye tu toh kya teri maa bhi chud jaaiye.",
    "jo hoyega ek sath hoyega, teri mummy ki bhosdi mai apne lund se dhoyega.",
    "mai hu tumahara jija, tumahari maa ka gandii bhosdi mai garma garam pizza.",
    "teri ma randi hai uspe mera kya kasur, teri ma ki chut chatwa de paisa dunga bharpur.",
    "aaj mai pagal ho gya, aur pagal hoke teri maa ko apne land per bithakar chod dunga koi nahin rok payega mujhe.",
    "ali bali chamatkar naam mera kalakar, teri ma ko chod chod ke bana dunga sarkar.",
    "aankho pe kajal sar pe bindi, teri mummy chut pe leti ha vendi, vendi gaya tut! teri behen ki kali kali chut.",
    "me subha likhta hoon, shaam likhta hoon, haalo haal tamam likhta hoon, mai subha likhta hoon, shaam likhta hoon, haalo haal tamam likhta hoon, mera land diwana hojay teri maiya ki kaale bhosda ko dekh kar, mai teri ma ki chut per mera bhaiyo ka name likhta hoon randi ke bachche",
    "randi ma ke randi bachche, chiti chadhi pahad per angrezo ka zaman tha, ke chiti chadhi pahad per angrezo ka zaman tha, angrezo ka zamana chala gya per mera lund teri maiya ki chut ka hi diwana tha.",
    "kach ka shisha niche gir kar tut gya, kach ka shisha niche gir ker tut gya, maine teri ma ki kali chut ka kali raat me choda tha usme mera thora sa lund ka paani chut gya ma ke lowde usse ek bachcha nikla randi ka bachcha"
]